server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        name: JSESSIONID

spring:
  thymeleaf:
    cache: false
  session:
    store-type: redis
    # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/study-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
#    打开对于PUT和DELETE请求方式的支持
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis-plus:
  #指定实体类所有包
  type-aliases-package: com.mengxuegu.web.entities

#日志级别，会打印sql语句
logging:
  level:
    com.mengxuegu.web.mapper: debug

mengxuegu:
  security:
    authentication:
      loginPage: /login/page
      loginProcessingUrl: /login/form
      usernameParameter: name
      passwordParameter: pwd
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT
      imageCodeUrl: /code/image
      mobileCodeUrl: /code/mobile
      mobilePage: /mobile/page
      tokenValidateSeconds: 604800